### PR TITLE
migrate to astro

### LINKED ISSUE #47: migrate to astro
we have many issue in nuxt so the goal is to migrate to stop this mess

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
Resolves #47 
/claim #47

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@riderx This is ready for review.

**Comment by riderx** [comment]
omg you are so fast ^^
i think the background of the website is not the same between here:
https://deploy-preview-48--captime.netlify.app/
and 
https://captime.app/

**Comment by rishi-raj-jain** [comment]
@riderx 

Right now in the codebase, I see bg-gray-900 which is leading to this. Let me know if I should go ahead and remove this?

> omg you are so fast ^^

Thank you <3

**Comment by riderx** [comment]
Merge and paid !

**Comment by rishi-raj-jain** [comment]
Thank you man! @riderx <3

**Pull request merged**
